version: "3"
services:
  mysql:
    container_name: wpb_mysql
    image: "mariadb:10.2"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "6033:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "12345"

  phpmyadmin:
    container_name: wpb_pma
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "12345"
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8088:80

  wordpress:
    container_name: wpb_wp
    image: wordpress
    ports:
      - "8000:80"
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "12345"
      WORDPRESS_DB_NAME: wordpress